---
- name: install nginx
  sudo: yes
  apt: pkg=nginx-full
       state=latest
       update_cache=yes
       cache_valid_time=3600

- name: ensure nginx is started
  sudo: yes
  service: name=nginx state=started

- name: configure nginx
  sudo: yes
  template: src=nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            owner=root
            group=root
            mode=0644
  notify:
    - reload nginx

- name: configure nginx https
  sudo: yes
  template: src=https-default.conf.j2
            dest=/etc/nginx/https-default.conf
            owner=root
            group=root
            mode=0644
  notify:
    - reload nginx

- name: configure nginx uwsgi params
  sudo: yes
  template: src=uwsgi_params.j2
            dest=/etc/nginx/uwsgi_params
            owner=root
            group=root
            mode=0644
  notify:
    - reload nginx

- name: make openssl dir
  sudo: yes
  file: path=/etc/nginx/ssl
        state=directory
        owner=root
        group=root
        mode=755

- name: prepare openssl dhparam
  sudo: yes
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  args:
    creates: /etc/nginx/ssl/dhparam.pem
  notify:
    - reload nginx

- name: setup nginx sites-enabled dir
  sudo: yes
  file: path=/etc/nginx/sites-enabled
        state=directory
        owner=deploy
        group=deploy

- name: delete default site
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default
        state=absent
        owner=deploy
        group=deploy
  notify:
    - reload nginx
