---
- name: install mysql
  sudo: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - mysql-common
    - mysql-server
    - libmysqlclient-dev

- name: configure mysql
  sudo: yes
  template: src=my.cnf.j2
            dest=/etc/mysql/my.cnf
            owner=root
            group=root
            mode=0644
  notify:
    - restart mysql
