---
- name: install python basics
  sudo: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - python-virtualenv
    - libxml2-dev
    - libxslt-dev
    - libmemcached-dev

- name: create /var/sw dir
  sudo: yes
  file: path=/var/sw owner=deploy group=deploy state=directory

# This is specifically run without sudo.
- name: setup python virtualenv
  command: virtualenv -p /usr/bin/python3.4 /var/sw/pyramid34 creates=/var/sw/pyramid34
