from unittest import TestCase

from ...views.cart import CheckoutForm


class TestCheckoutValidator(TestCase):
    maxDiff = 2000

    def test_saved_cc(self):
        self.assertEqual(CheckoutForm.to_python({
            'shipping.country_code': 'us',
            'shipping.first_name': 'Ben',
            'shipping.last_name': 'Bitdiddle',
            'shipping.company': '',
            'shipping.address1': '123 Main St',
            'shipping.address2': '',
            'shipping.city': 'Portland',
            'shipping.state': 'OR',
            'shipping.postal_code': '97214',
            'shipping.phone': '555-555-1212',
            'cc.use_saved': 'yes',
            'cc.number': '',
            'cc.expires_month': '01',
            'cc.expires_year': '2015',
            'cc.code': '',
            'cc.save': '1',
            'cc.billing.country_code': 'us',
            'cc.billing.first_name': 'Ben',
            'cc.billing.last_name': 'Bitdiddle',
            'cc.billing.company': '',
            'cc.billing.address1': '44 Bella Vista Drive',
            'cc.billing.address2': 'Suite 14',
            'cc.billing.city': 'Portland',
            'cc.billing.state': 'OR',
            'cc.billing.postal_code': '97215',
            'cc.billing.phone': '555-555-1212',
            'email': 'ben@example.com',
            'comments': 'Hello, world.',
        }), {
            'shipping': {
                'country_code': 'us',
                'first_name': 'Ben',
                'last_name': 'Bitdiddle',
                'company': '',
                'address1': '123 Main St',
                'address2': '',
                'city': 'Portland',
                'state': 'OR',
                'postal_code': '97214',
                'phone': '555-555-1212',
            },
            'cc': 'saved',
            'billing_same_as_shipping': False,
            'non_physical': False,
            'email': 'ben@example.com',
            'comments': 'Hello, world.',
        })

    def test_unsaved_cc(self):
        self.assertEqual(CheckoutForm.to_python({
            'shipping.country_code': 'us',
            'shipping.first_name': 'Ben',
            'shipping.last_name': 'Bitdiddle',
            'shipping.company': '',
            'shipping.address1': '123 Main St',
            'shipping.address2': '',
            'shipping.city': 'Portland',
            'shipping.state': 'OR',
            'shipping.postal_code': '97214',
            'shipping.phone': '555-555-1212',
            'cc.use_saved': 'no',
            'cc.number': '4111 1111 1111 1111',
            'cc.expires_month': '05',
            'cc.expires_year': '2020',
            'cc.code': '123',
            'cc.save': '1',
            'cc.billing.country_code': 'us',
            'cc.billing.first_name': 'Ben',
            'cc.billing.last_name': 'Bitdiddle',
            'cc.billing.company': '',
            'cc.billing.address1': '44 Bella Vista Drive',
            'cc.billing.address2': 'Suite 14',
            'cc.billing.city': 'Portland',
            'cc.billing.state': 'OR',
            'cc.billing.postal_code': '97215',
            'cc.billing.phone': '555-555-1212',
            'email': 'ben@example.com',
            'comments': 'Hello, world.',
        }), {
            'shipping': {
                'country_code': 'us',
                'first_name': 'Ben',
                'last_name': 'Bitdiddle',
                'company': '',
                'address1': '123 Main St',
                'address2': '',
                'city': 'Portland',
                'state': 'OR',
                'postal_code': '97214',
                'phone': '555-555-1212',
            },
            'cc': {
                'number': '4111 1111 1111 1111',
                'expires_month': '05',
                'expires_year': '2020',
                'code': '123',
                'save': True,
                'billing': {
                    'country_code': 'us',
                    'first_name': 'Ben',
                    'last_name': 'Bitdiddle',
                    'company': '',
                    'address1': '44 Bella Vista Drive',
                    'address2': 'Suite 14',
                    'city': 'Portland',
                    'state': 'OR',
                    'postal_code': '97215',
                    'phone': '555-555-1212',

                },
            },
            'billing_same_as_shipping': False,
            'non_physical': False,
            'email': 'ben@example.com',
            'comments': 'Hello, world.',
        })

    def test_non_physical_unsaved_cc(self):
        self.assertEqual(CheckoutForm.to_python({
            'non_physical': '1',
            'cc.use_saved': 'no',
            'cc.number': '4111 1111 1111 1111',
            'cc.expires_month': '05',
            'cc.expires_year': '2020',
            'cc.code': '123',
            'cc.save': '1',
            'cc.billing.country_code': 'us',
            'cc.billing.first_name': 'Ben',
            'cc.billing.last_name': 'Bitdiddle',
            'cc.billing.company': '',
            'cc.billing.address1': '44 Bella Vista Drive',
            'cc.billing.address2': 'Suite 14',
            'cc.billing.city': 'Portland',
            'cc.billing.state': 'OR',
            'cc.billing.postal_code': '97215',
            'cc.billing.phone': '555-555-1212',
            'email': 'ben@example.com',
            'comments': 'Hello, world.',
        }), {
            'shipping': {
                'country_code': 'us',
                'first_name': 'Ben',
                'last_name': 'Bitdiddle',
                'company': '',
                'address1': '44 Bella Vista Drive',
                'address2': 'Suite 14',
                'city': 'Portland',
                'state': 'OR',
                'postal_code': '97215',
                'phone': '555-555-1212',
            },
            'cc': {
                'number': '4111 1111 1111 1111',
                'expires_month': '05',
                'expires_year': '2020',
                'code': '123',
                'save': True,
                'billing': {
                    'country_code': 'us',
                    'first_name': 'Ben',
                    'last_name': 'Bitdiddle',
                    'company': '',
                    'address1': '44 Bella Vista Drive',
                    'address2': 'Suite 14',
                    'city': 'Portland',
                    'state': 'OR',
                    'postal_code': '97215',
                    'phone': '555-555-1212',

                },
            },
            'billing_same_as_shipping': False,
            'non_physical': True,
            'email': 'ben@example.com',
            'comments': 'Hello, world.',
        })
